//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeVista2._0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_attendance
    {
        public int id { get; set; }
        public string employee_id { get; set; }
        public string department { get; set; }
        public string shift { get; set; }
       
        public string message { get; set; }
        public System.DateTime date { get; set; }
        public System.TimeSpan check_in { get; set; }
        public string in_status { get; set; }
        public System.TimeSpan check_out { get; set; }
        public string out_status { get; set; }
        public System.DateTime created_at { get; set; }
    }
}
