//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeVista2._0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_department
    {
        public int id { get; set; }
        public string department_id { get; set; }
        public string department_name { get; set; }
        public byte status { get; set; }
        public System.DateTime created_at { get; set; }
    }
}
