//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeVista2._0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblleaf
    {
        public int Lid { get; set; }
        public string LeaveType { get; set; }
        public string ToDate { get; set; }
        public string FromDate { get; set; }
        public int duration { get; set; }
        public string Description { get; set; }
        public System.DateTime PostingDate { get; set; }
        public string AdminRemark { get; set; }
        public string AdminRemarkDate { get; set; }
        public int Status { get; set; }
        public int IsRead { get; set; }
        public int employee_id { get; set; }
    }
}
